
version: '2'

services:
  zookeeper:
    image: trivadisbds/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: trivadisbds/kafka:0.11.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"    
      KAFKA_CREATE_TOPICS: "test:1:3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
